// Report file generated by ORMCustomTool.
// Any generation errors will appear as #error lines in this file,
// followed by the exception message and stack trace.
#error This project type is not recognized by the NORMA generator. The ORMCustomTool value in the CustomTool property for this file is only supported with the classic .NET project format. Please use a project type with (.NET Framework) in the name to run the NORMA generators.
