<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MySqlConnector" Version="2.6.2" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="ORMModel1._ORMCustomToolReport.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>ORMModel1.orm</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="ORMModel1.orm">
      <Generator>ORMCustomTool</Generator>
      <LastGenOutput>ORMModel1._ORMCustomToolReport.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>
